"""
channel_measured.py - AUTOGENERATED by analyze_returns.py

Drop-in replacement for channel.py that reproduces real platform behaviour
using quantization tables measured from actual round trips, instead of
approximating with Pillow's quality=N.

Do not hand-edit; regenerate from fresh measurements instead.
"""

from __future__ import annotations

import io
from pathlib import Path

from PIL import Image, ImageOps

# platform -> dict(max_width, luma_qt, chroma_qt, subsampling)
MEASURED_PROFILES = {
    "whatsapp": {
        "max_width": 1600,
        "subsampling": 2,  # 4:2:0
        "est_quality": 67.0,
        "luma_qt": [6, 6, 6, 7, 10, 15, 22, 34, 6, 7, 8, 11, 14, 16, 21, 30, 6, 8, 10, 12, 17, 25, 36, 54, 7, 11, 12, 16, 21, 30, 42, 62, 10, 14, 17, 21, 28, 38, 52, 76, 15, 16, 25, 30, 38, 50, 68, 95, 22, 21, 36, 42, 52, 68, 90, 124, 34, 30, 54, 62, 76, 95, 124, 167],
        "chroma_qt": [6, 6, 6, 7, 10, 15, 22, 34, 6, 7, 8, 11, 14, 16, 21, 30, 6, 8, 10, 12, 17, 25, 36, 54, 7, 11, 12, 16, 21, 30, 42, 62, 10, 14, 17, 21, 28, 38, 52, 76, 15, 16, 25, 30, 38, 50, 68, 95, 22, 21, 36, 42, 52, 68, 90, 124, 34, 30, 54, 62, 76, 95, 124, 167],
    },
}


def simulate(input_path, profile_name, output_path=None) -> bytes:
    """Resize + re-encode using the platform's MEASURED quantization tables."""
    prof = MEASURED_PROFILES[profile_name]
    img = Image.open(Path(input_path))
    img.load()
    img = ImageOps.exif_transpose(img)
    if img.mode == "RGBA":
        bg = Image.new("RGB", img.size, (255, 255, 255))
        bg.paste(img, mask=img.split()[3])
        img = bg
    elif img.mode not in ("RGB", "L"):
        img = img.convert("RGB")
    mw = prof["max_width"]
    if mw and img.width > mw:
        ratio = mw / img.width
        img = img.resize((mw, max(1, round(img.height * ratio))), Image.Resampling.LANCZOS)
    qt = [prof["luma_qt"]]
    if "chroma_qt" in prof:
        qt.append(prof["chroma_qt"])
    buf = io.BytesIO()
    img.save(buf, format="JPEG", qtables=qt, subsampling=prof["subsampling"], optimize=False)
    data = buf.getvalue()
    if output_path is not None:
        Path(output_path).write_bytes(data)
    return data
